# FashionGen data nums: 60147

includes:
- ./e2e_contrastive.yaml

dataset_config:
  fashiongen:
    training_head_type: contrastive


model_config:
  FashionFAE:
    image_encoder:
      type: vit_image_encoder
      params:
        name: vit
        pretrained_model_name: google/vit-base-patch16-224-in21k
        random_init: false
        gradient_checkpointing: false
    visual_embedding_dim: 768
    lr_multiplier: 1

training:
  experiment_name: mpfc+mlm_global+icc_finet2_contrastive
  batch_size: 128
  lr_scheduler: true
  max_updates: 75120
  log_interval: 10
  checkpoint_interval: 9390
  evaluation_interval: 939
  early_stop:
    criteria: fashiongen/r@k_kaleido/avg
    minimize: false
  wandb:
    enabled: true

evaluation:
  metrics:
    - r@k_general
    - r@k_kaleido

run_type: train_val

checkpoint:
  resume_pretrained: true
  resume_file: save/mpfc+mlm_global+icc/best.ckpt
  pretrained_state_mapping:
    image_encoder: image_encoder
    model.bert: model.bert
